### ISSUE TITLE
tmux-tcl manpage isn't installed

### ISSUE THREAD

**Issue by ShadowKyogre** [ershov/tmux#2]
Hey there! Just thought I should let you know that the manpage for the extensions (tmux-tcl) isn't installed after compile. The most relevant lines for this are here:

https://github.com/ershov/tmux/blob/master/Makefile.am#L244-L255

**Comment by ShadowKyogre** [comment]
Got fix for it, just need to open a PR

**Comment by ershov** [comment]
Merged. Thanks!
