### ISSUE TITLE
"unknown option: tcl" on OS X

### ISSUE THREAD

**Issue by jeromedalbert** [ershov/tmux#4]
Hi, I have some problems trying to make tcl work with this tmux fork on OS X.

After following the [BUILD instructions](https://github.com/ershov/tmux/blob/master/README-tmux-scripting.pod#build) in the README, I tried to do `set tcl 1` in tmux but I got the error message `unknown option: tcl`. So apparently tcl is not installed or configured.

The README says: "If a package is installed in another location, try first specifying PKG_CONFIG_PATH: `$ PKG_CONFIG_PATH=[path to dir with tcl.pl] ./configure`"

I am on Mac OS X and I can't find tcl, although OS X apparently comes with it. I did a `sudo find / -type f -name "tcl.pl"` which gave nothing. So I decided to install it with the homebrew package manager: `brew install tcl-tk` from [Homebrew/homebrew-dupes](https://github.com/Homebrew/homebrew-dupes) (a repo of system duplicates). It has installed it in `/usr/local/opt/tcl-tk`, but there is no "tcl.pl" anywhere inside that folder, so I don't know where to proceed next.

PS:
If it helps, here is the output of `brew info tcl-tk`:

```
Tk installs some X11 headers and OS X provides an (older) Tcl/Tk.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/tcl-tk/lib
    CPPFLAGS: -I/usr/local/opt/tcl-tk/include
```

Maybe I need to use these flags somehow?

**Comment by ershov** [comment]
Are you sure you cloned this repository https://github.com/ershov/tmux.git and branch 'master' is checked out?
This is easy to see: is there a file named 'tcl.c'?

**Comment by jeromedalbert** [comment]
Yes there is a `tcl.c`, `tcl.m4` and `tcl.o` and I am on `master`. It looks like doing a `killall tmux` fixed my problem though! 🤐 `set tcl 1` does not output any error now. Sorry for bothering you with that!

Although if I may ask about another (maybe related) problem, I tried to add this basic mapping in my `~/.tmux.conf` just to see if it worked:

```
bind-key -t vi-copy J tcl { cursor-down }
```

And I got a `not enough arguments` when sourcing.

And when I try one of your examples in the README:

```
# Mark the current word in vi-copy mode
bind-key -t vi-copy M-Enter tcl {
  clear-selection
  previous-space
  begin-selection
  next-space-end
}
```

I get 

```
/Users/jerome/.tmux.conf:55: unknown command: clear-selection
/Users/jerome/.tmux.conf:56: unknown command: previous-space
/Users/jerome/.tmux.conf:57: unknown command: begin-selection
/Users/jerome/.tmux.conf:58: unknown command: next-space-end
/Users/jerome/.tmux.conf:59: unknown command: }
```

The last error seem to happen when splitting on multiple lines. Any idea why tcl does not seem to work in both examples?

My end goal is to have something like `bind-key -t vi-copy J tcl { cursor-down; cursor-down; cursor-down; cursor-down; cursor-down }`, so that when I press J or K it will go 5 lines down or up.

**Comment by ershov** [comment]
This is because your .tmux.conf is still in tmux's wacky language.
I suggest you to add this line at the end of .tmux.conf:

```
if-shell -F "#{have_tcl}" "tcl source ~/.tmux.tcl"
```

and put all your tcl commands in .tmux.tcl

This way you also keep compatibility with non-tcl tmux versions.

**Comment by jeromedalbert** [comment]
Oh, ok. I should have read the README more thoroughly.

Since I don't mind about not being compatible for now, this is what I ended up with in my `.tmux.conf`:

```
# multi-commands in modes only work with this patched tmux that allows tcl
# scripting: https://github.com/ershov/tmux
set tcl 1
tcl "bind-key -t vi-copy J tcl { \
  cursor-down; cursor-down; cursor-down; cursor-down; cursor-down \
}"
tcl "bind-key -t vi-copy K tcl { \
  cursor-up; cursor-up; cursor-up; cursor-up; cursor-up \
}"
```

Works like a charm. Thanks for your help and for this great fork!

**Comment by ershov** [comment]
Cool!
I'm glad I helped.

I should note that it's not necessary to do `set tcl 1` for this to work.
The effect of this command is switching tmux command line (`C-b :`) into tcl mode.
So if you are not confident with using tcl there, just remove that line.

And if you don't care about non-tcl version compatibility, I'd still recommend to put this line at the end of .tmux.conf: `tcl source ~/.tmux.tcl` and just use tcl in that file.

Believe me, you have just only started. More ideas are coming! :)

**Comment by jeromedalbert** [comment]
Well I just pair-programmed with a colleague via tmux and now I get why doing the `if-shell -F "#{have_tcl}" "tcl source ~/.tmux.tcl"` was important! Since my pair programming program was a fork of tmux that did not have tcl.
